project:
  type: website
  output-dir: docs

website:
  title: "Abhishek Kumar"
  navbar:
    left:
      - text: About
        href: about.qmd
      - text: Blog
        href: index.qmd
      - text: Publications
        href: publications.qmd
    right: 
      - icon: github
        href: https://github.com/kumar-a
      - icon: twitter
        href: https://twitter.com/abkumar_
format:
  html:
    theme: cosmo
    css: styles.css



