project:
  type: website
  output-dir: docs

website:
  title: "Abhishek Kumar"
  navbar:
    left:
      - icon: trophy
        text: Accomplishments
        href: accomplishments.qmd
      - icon: pen
        text: Blog
        href: blog.qmd
      - icon: journals
        text: Publications
        href: publications.qmd
      - icon: mic
        text: Talks
        href: talks.qmd
        
    right: 
      - icon: github
        href: https://github.com/kumar-a
      - icon: twitter
        href: https://twitter.com/abkumar_
format:
  html:
    theme: cosmo
    css: styles.css



